sudo: false
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - Gemfile
before_install: gem install bundler -v 1.15.4
